### ISSUE TITLE
finch build fails when using local base image

### ISSUE THREAD

**Issue by vsiravar** [runfinch/finch#91] opened 2022-12-06 03:57 UTC
**Describe the bug**
Briefly describe the problem you are having.
While building images with locally built/stored images, the build stumbles with an error and does not build an image.  

Host info 
```
siravara@bcd074105a94 vishwas-tests % uname -a
Darwin bcd074105a94.ant.amazon.com 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64
```
**Steps to reproduce**
A clear, step-by-step set of instructions to reproduce the bug.
Base image docker file
```
siravara@bcd074105a94 vishwas-tests % cat Dockerfile_parent 
FROM public.ecr.aws/docker/library/alpine:3.13
```
Build base image
```
siravara@bcd074105a94 vishwas-tests % finch build -f Dockerfile_parent -t baseimage:latest .

siravara@bcd074105a94 vishwas-tests % finch images
REPOSITORY    TAG       IMAGE ID        CREATED         PLATFORM       SIZE       BLOB SIZE
baseimage     latest    1ebab426c374    10 hours ago    linux/arm64    6.6 MiB    2.6 MiB
```
Dockerfile that references the base image 
```
siravara@bcd074105a94 vishwas-tests % cat Dockerfile_child 
FROM baseimage:latest
```

Build image which references `baseimage:latest`
```
siravara@bcd074105a94 vishwas-tests % finch build -f Dockerfile_child -t child:latest .  
[+] Building 1.1s (3/3) FINISHED                                                
 => [internal] load build definition from Dockerfile_child                 0.0s
 => => transferring dockerfile: 66B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/library/baseimage:latest  1.0s
------
 > [internal] load metadata for docker.io/library/baseimage:latest:
------
Dockerfile_child:1
--------------------
   1 | >>> FROM baseimage:latest
   2 |     
   3 |     
--------------------
error: failed to solve: baseimage:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
FATA[0001] unrecognized image format                    
FATA[0001] exit status 1                                
```
**Expected behaviour**
Description of what you expected to happen.
Building from a local base image should succeed and produce an image with tag `child:latest`. 

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**
The build is successful using `nerdctl` with `Fedora`as the guest OS on lima.

**Comment by AkihiroSuda** [comment] 2022-12-06 12:29
Seems a duplicate of
- https://github.com/runfinch/finch/issues/71

**Comment by ChandruShetty** [comment] 2022-12-06 22:36
Duplicate issue of https://github.com/runfinch/finch/issues/71

**Closed by ChandruShetty** 2022-12-06 22:36 UTC
Labels: bug
