### ISSUE TITLE
"finch vm init": failed to setup ssh client: ssh: handshake failed: ssh: unable to authenticate

### ISSUE THREAD

**Issue by sparkling** [runfinch/finch#132] opened 2022-12-24 15:57 UTC
**Describe the bug**
Followed the instructions in the Finch README. Getting above SSH error when running `finch vm init`

**Steps to reproduce**
Run `brew install --cask finch`, then run `finch vm init`

**Expected behavior**
For Finch to install and initialise successfully. 

**Screenshots or logs**
1) brew install --cask finch, 
######################################################################## 100.0%
==> Installing Cask finch
==> Running installer for finch; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Password:
installer: Package name is Finch
installer: Installing at base path /
installer: The install was successful.
🍺  finch was successfully installed!

2) finch vm init
INFO[0000] Using default values due to missing config file at "/Users/henrik.pettersen/.finch/finch.yaml"
INFO[0000] "/Users/henrik.pettersen/.finch" directory doesn't exist, attempting to create it
INFO[0000] binaries directory doesn't exist
INFO[0000] Requesting root access to finish network dependency configuration
INFO[0000] sudoers file not found: open /etc/sudoers.d/finch-lima: no such file or directory
INFO[0000] Initializing and starting Finch virtual machine...
INFO[0069] Finch virtual machine started successfully
FATA[0069] failed to setup ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Additional context**
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	8419.60.44
  OS Loader Version:	7459.141.1
  Serial Number (system):	FVFGW23LQ05N
  Hardware UUID:	1FB6F3D7-2931-523A-9A3A-09F8A497D8AB
  Provisioning UDID:	00008103-001844A43A33001E
  Activation Lock Status:	Disabled

OS: MacOS Monterey 12.6.2

**Comment by azhouwd** [comment] 2022-12-26 04:51
Duplicate of https://github.com/runfinch/finch/issues/38#issue-1461983765

**Comment by KevinLiAWS** [comment] 2023-01-26 20:38
Close the duplicate issue and track with #38

**Closed by KevinLiAWS** 2023-01-26 20:38 UTC
Labels: bug
