### ISSUE TITLE
Feedback: Slow build

### ISSUE THREAD

**Issue by dlaidlaw** [runfinch/finch#702] opened 2023-11-22 17:26 UTC
**Describe the bug**
Not so much a bug as feedback about a step that is extremely slow compared to the equivalent docker command.

Just providing this is feedback for what I have experienced in a typical usage.

**Steps to reproduce**
finch build . -t al2023:finch
vs
docker build . -t al2023:docker

See below for the Dockerfile.

**Expected behavior**
The build command to finish in near the same amount of time as the equivalent docker command.

The `RUN dnf` line of the Dockerfile (line 4) took:

**With finch: 4572 seconds**. (one hour, 18 minutes)
With Docker: 50 seconds

**Screenshots or logs**

[finch-support-20231122131420.zip](https://github.com/runfinch/finch/files/13442679/finch-support-20231122131420.zip)

**Additional context**

Running on Mac OS

The Dockerfile:
```Dockerfile
FROM public.ecr.aws/amazonlinux/amazonlinux:2023 as build

RUN mkdir /sysroot
RUN dnf --releasever=$(rpm -q system-release --qf '%{VERSION}') \
  --installroot /sysroot \
  -y \
  --setopt=install_weak_deps=False \
  install \
  bash awscli-2 openssl openssl-devel wget jq unzip tar gzip vim nano bash-completion less findutils

FROM scratch
COPY --from=build /sysroot /
WORKDIR /root
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENTRYPOINT ["/usr/bin/bash"]
```

Thanks for looking.

**Comment by mharwani** [comment] 2023-11-24 02:16
Hi, thank you for the feedback. I'm able to reproduce this on my machine. Build takes 6314s (1hr, 45m) with Finch and 66s with Docker. Usually, builds are not this slow, so this seems specific to the Dockerfile. Looking into the root cause.

**Comment by dlaidlaw** [comment] 2023-11-27 16:39
In case you are wondering where the dnf command came from, see this AWS documentation: https://docs.aws.amazon.com/linux/al2023/ug/barebones-containers.html

**Comment by Shubhranshu153** [comment] 2024-12-13 02:48
Retested this to do a comparative study with present finch. 
```
finch build -t build-benchmark .  0.11s user 0.16s system 0% cpu 1:23.91 total
```

```
docker build -t build-benchmark .  0.56s user 0.72s system 1% cpu 2:04.67 total
```

Closing this ticket.

**Closed by Shubhranshu153** 2024-12-13 02:48 UTC
Labels: bug
