### ISSUE TITLE
Change name as it is already used by an existing linux package: "A text-based user interface for Pidgin"

### ISSUE THREAD

**Issue by good92** [runfinch/finch#301] opened 2023-03-17 10:09 UTC
**What is the problem you're trying to solve?.**
A clear and concise description of the use case for this feature. Please provide an example, if possible.

> Change name as it is already used by an existing linux package: "A text-based user interface for Pidgin"
https://yum-info.contradodigital.com/view-package/base/finch/

**Describe the feature you'd like**
A clear and concise description of what you'd like to happen.

**Additional context**

**Comment by ahsan-z-khan** [comment] 2023-03-20 20:05
Closing as duplicate of Issue #26

**Closed by ahsan-z-khan** 2023-03-20 20:05 UTC
